version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tictactoe-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_DATABASE: tictactoe
    networks:
      - tictactoe-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/tictactoe --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    container_name: tictactoe-user-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongodb:27017/tictactoe
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - tictactoe-network
    restart: unless-stopped

  game-service:
    build: ./game-service
    container_name: tictactoe-game-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://mongodb:27017/tictactoe
      USER_SERVICE_URL: http://user-service:3001
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - tictactoe-network
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    container_name: tictactoe-api-gateway
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      USER_SERVICE_URL: http://user-service:3001
      GAME_SERVICE_URL: http://game-service:3002
    depends_on:
      - user-service
      - game-service
    networks:
      - tictactoe-network
    restart: unless-stopped

  web-client:
    image: nginx:alpine
    container_name: tictactoe-web-client
    ports:
      - "8080:80"
    volumes:
      - ./web-client:/usr/share/nginx/html:ro
    depends_on:
      - api-gateway
    networks:
      - tictactoe-network
    restart: unless-stopped

networks:
  tictactoe-network:
    driver: bridge

volumes:
  mongodb_data:
