services:
  mongodb:
    image: mongo:latest
    container_name: ttt-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - ttt-network

  user-service:
    build: ./user-service
    container_name: ttt-user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - ttt-network

  api-gateway:
    build: ./api-gateway
    container_name: ttt-api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:3001
      - GAME_SERVICE_URL=http://game-service:3002
    depends_on:
      - user-service
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    networks:
      - ttt-network

networks:
  ttt-network:
    driver: bridge

volumes:
  mongodb_data: